export const AI_DEFAULT_PROVIDERS = ['gemini', 'openai'] as const;

export type AiDefaultProvider = (typeof AI_DEFAULT_PROVIDERS)[number];
export type QueueDriver = 'memory' | 'bullmq';
export type AppRuntimeRole = 'api' | 'worker';
export type AppEnvironment = 'development' | 'test' | 'staging' | 'production';

export interface EnvironmentVariables {
  NODE_ENV: 'development' | 'test' | 'production';
  APP_ENVIRONMENT?: AppEnvironment;
  PORT: number;
  APP_VERSION?: string;
  APP_ROLE?: AppRuntimeRole;
  SECRET_ENCRYPTION_KEY: string;
  DATABASE_URL: string;
  DIRECT_URL: string;
  JWT_ACCESS_SECRET: string;
  JWT_REFRESH_SECRET: string;
  JWT_ACCESS_EXPIRES_IN_SECONDS: number;
  JWT_REFRESH_EXPIRES_IN_SECONDS: number;
  AUTH_BYPASS_IN_TEST?: boolean;
  AUTH_ALLOW_DEV_BOOTSTRAP?: boolean;
  AUTH_RATE_LIMIT_WINDOW_MS?: number;
  AUTH_RATE_LIMIT_MAX_REQUESTS?: number;
  WEBHOOK_RATE_LIMIT_WINDOW_MS?: number;
  WEBHOOK_RATE_LIMIT_MAX_REQUESTS?: number;
  CORS_ALLOWED_ORIGINS?: string;
  CORS_ALLOW_CREDENTIALS?: boolean;
  TRUST_PROXY?: boolean;
  API_REQUEST_BODY_LIMIT?: string;
  SECURITY_HEADERS_ENABLED?: boolean;
  AI_DEFAULT_PROVIDER: AiDefaultProvider;
  GEMINI_API_KEY?: string;
  GEMINI_MODEL?: string;
  OPENAI_API_KEY?: string;
  OPENAI_MODEL?: string;
  AI_TIMEOUT_MS?: number;
  AI_MAX_RETRIES?: number;
  WHATSAPP_SEND_MAX_RETRIES?: number;
  WHATSAPP_SEND_RETRY_BASE_DELAY_MS?: number;
  OUTBOUND_MIN_INTERVAL_MS?: number;
  INBOUND_RATE_LIMIT_PER_WINDOW?: number;
  INBOUND_RATE_LIMIT_WINDOW_MS?: number;
  EXECUTION_QUEUE_MAX_RETRIES?: number;
  EXECUTION_QUEUE_RETRY_BASE_DELAY_MS?: number;
  QUEUE_DRIVER?: QueueDriver;
  REDIS_URL?: string;
  QUEUE_PREFIX?: string;
  QUEUE_INLINE_WORKERS?: boolean;
  QUEUE_INBOUND_CONCURRENCY?: number;
  QUEUE_AI_DECISION_CONCURRENCY?: number;
  QUEUE_OUTBOUND_CONCURRENCY?: number;
  QUEUE_JOB_REMOVE_ON_COMPLETE?: number;
  QUEUE_JOB_REMOVE_ON_FAIL?: number;
  WHATSAPP_ACCESS_TOKEN?: string;
  WHATSAPP_PHONE_NUMBER_ID?: string;
  WHATSAPP_BUSINESS_ACCOUNT_ID?: string;
  WHATSAPP_WEBHOOK_VERIFY_TOKEN: string;
  WHATSAPP_APP_SECRET?: string;
  WHATSAPP_WEBHOOK_SIGNATURE_REQUIRED?: boolean;
  WHATSAPP_PROVIDER_TIMEOUT_MS?: number;
  WHATSAPP_ENV_FALLBACK_ENABLED?: boolean;
  META_GRAPH_API_VERSION: string;
  WEBSITE_FETCH_TIMEOUT_MS?: number;
  WEBSITE_FETCH_MAX_PAGES?: number;
  WEBSITE_FETCH_MAX_RESPONSE_BYTES?: number;
  INSTAGRAM_ACCESS_TOKEN?: string;
  INSTAGRAM_USER_ID?: string;
  INSTAGRAM_GRAPH_API_VERSION?: string;
  INSTAGRAM_MEDIA_LIMIT?: number;
  INSTAGRAM_PROVIDER_TIMEOUT_MS?: number;
  INSTAGRAM_ENV_FALLBACK_ENABLED?: boolean;
  RESEND_API_KEY?: string;
  EMAIL_PROVIDER_TIMEOUT_MS?: number;
  EMAIL_FROM_ADDRESS?: string;
  APP_BASE_URL?: string;
  SENTRY_DSN?: string;
  SENTRY_ENABLED?: boolean;
  SWAGGER_ENABLED?: boolean;
  SWAGGER_PATH?: string;
  WEBHOOK_TEST_TOOL_ENABLED?: boolean;
}
